version: '3.4'
name: translator

services:
  translate:
    build:
      context: .
    command: uvicorn server:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    healthcheck:
      test: curl http://localhost:8080
